apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: "hpa-{{ .Release.Name }}"
spec:
  maxReplicas: {{ .Values.maxReplicas }}
  minReplicas: {{ .Values.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "deployment-{{ .Release.Name }}"
  targetCPUUtilizationPercentage: {{ .Values.targetCPUUtilizationPercentage }}
